# Waldyr Faustini - FE630 - Assignment 2

## Prof. Papa Momar Ndiaye - FE630 Portfolio Theory and Applications

## 2 Eingenvalues and Eigenvectors

###  1.

We have the matrix **A**:

$$ A = \begin{bmatrix} 1 & 2 & 1 \\ 2 & 1 & 1 \\ 1 & 1 & 2 \end{bmatrix}$$

- So let's starting calculating the **Characteristic Polynomial of A**:

$$p(\lambda)= det (A- \lambda I)$$

$$p(\lambda)= det\begin{bmatrix} 1-\lambda & 2 & 1 \\ 2 & 1-\lambda & 1 \\ 1 & 1 & 2-\lambda \end{bmatrix}$$

$$p(\lambda) = +[(1-\lambda).(1-\lambda).(2-\lambda)+(2.1.1)+(1.2.1)]-[(1.(1-\lambda).1+1.(1-\lambda)+2.2.(2-\lambda)]$$

$$p(\lambda) = -(\lambda-4).(\lambda+1).(\lambda-1)$$

So, rearranging the terms we have:

$$\boxed { p(\lambda) = -\lambda^3 + 4\lambda^2 + \lambda - 4}$$

- Now we can calculate the **Eingevalues**:

Considering the equation of Characteristic Polynomial of A, we have: $p(\lambda) = -(\lambda-4).(\lambda+1).(\lambda-1)$ or $p(\lambda) = -\lambda^3 + 4\lambda^2 + \lambda - 4$

We have to find the $\lambda$'s to turn $p(\lambda) = 0$. So, using :$p(\lambda) = -(\lambda-4).(\lambda+1).(\lambda-1) = 0$

We can easily identify $\boxed {\lambda_{1} = 4}$, $\boxed {\lambda_{2} = -1}$ and $\boxed {\lambda_{3} = +1}$ as eingevalues for this $p(\lambda)$

- For each **Eingevalue** we have one **Eingevector**. So we have 3 Eingevectors here.

For $\lambda_{1} = 4$  we have :
  $$\vec{p_{1}} = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}$$

For $\lambda_{2} = -1$  we have :
  $$\vec{p_{2}} = \begin{bmatrix} -1 \\ 1 \\ 0 \end{bmatrix}$$

For $\lambda_{3} = -1$  we have :
  $$\vec{p_{3}} = \begin{bmatrix} -1 \\ -1 \\ 2 \end{bmatrix}$$

So the 3 Eingevectors are:

$$\begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix} , \begin{bmatrix} -1 \\ 1 \\ 0 \end{bmatrix} , \begin{bmatrix} -1 \\ -1 \\ 2 \end{bmatrix}$$

###  2.

All the 3 eingevectors are orthogonal, it's a quick check just calculating the scalar product between them:

$$\vec p_{1} \cdot \vec p_{3} = 1.(-1) + 1.(-1) + 1.2 = -1 -1 +2 = 0$$

$$\vec p_{1} \cdot \vec p_{2} = 1.(-1) + 1.(1) + 1.0 = -1 +1 +0 = 0$$

$$\vec p_{3} \cdot \vec p_{2} = (-1).(-1) + (-1).1 + 2.0 = +1 -1 +0 = 0$$


So, now we are sure all the vectors are orthogonal, but we need the vectors be orthonormal. So, each vector need to lenght 1.
So, we first need to calculate all the norms.

$|\vec p_{1}| = \sqrt{1^2 +1^2+1^2} = \sqrt{3}$

$|\vec p_{2}| = \sqrt{(-1)^2 +1^2+0^2} = \sqrt{2}$

$|\vec p_{3}| = \sqrt{(-1)^2 +(-1)^2+2^2} = \sqrt{6}$

So if we multiplicate each vector by $\frac{1}{|vector|}$, we will normalize $|\vec p_{1}|, |\vec p_{2}|$  and  $|\vec p_{3}|$

- Normalizing $\vec{p_{1}}$ we have to multiply $\frac{1}{\sqrt{3}}\cdot\vec{p_{1}}$:

$$\frac{1}{\sqrt{3}}\cdot\begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix} = \begin{bmatrix} \frac{1}{\sqrt{3}} \\ \frac{1}{\sqrt{3}} \\ \frac{1}{\sqrt{3}} \end{bmatrix} $$

- Normalizing $\vec{p_{2}}$ we have to multiply $\frac{1}{\sqrt{2}}\cdot\vec{p_{2}}$:

$$\frac{1}{\sqrt{2}}\cdot\begin{bmatrix} -1 \\ 1 \\ 0 \end{bmatrix} = \begin{bmatrix} \frac{-1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \\ 0 \end{bmatrix} $$

- Normalizing $\vec{p_{3}}$ we have to multiply $\frac{1}{\sqrt{6}}\cdot\vec{p_{3}}$:

$$\frac{1}{\sqrt{6}}\cdot\begin{bmatrix} -1 \\ -1 \\ 2 \end{bmatrix} = \begin{bmatrix} \frac{-1}{\sqrt{6}} \\ \frac{-1}{\sqrt{6}} \\ \frac{2}{\sqrt{6}} \end{bmatrix} $$

So now we can have the matrix ${P}$ orthornormalized:

$${P} = \begin{bmatrix} \frac{1}{\sqrt{3}} & \frac{-1}{\sqrt{2}} & \frac{-1}{\sqrt{6}} \\ \frac{1}{\sqrt{3}} & \frac{1}{\sqrt{2}} & \frac{-1}{\sqrt{6}} \\ \frac{1}{\sqrt{3}} & 0  & \frac{2}{\sqrt{6}} \end{bmatrix} $$

We have all the Eingevalues, so it's easy to get the diagonal matrix D. Each eingevalue will be an element of the diagonal, the other elements will be zero. So, the diaginal matrix D is:

$$ {D} = \begin{bmatrix} 4 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$

Now we calculate the matrix $P^{-1}$, i used the normal process to write an identity matrix 3x3 on the right and then doing some algebric operations between line and columns we can move this identity matrix to the left. So, the final result for $P^{-1}$ is :

$${P^{-1}} = \begin{bmatrix} \frac{\sqrt{3}}{2} & \frac{\sqrt{3}}{2} & 0 \\ \frac{-1}{2\sqrt{2}} & \frac{3}{2\sqrt{2}} & \frac{-1}{\sqrt{2}} \\ \frac{-\sqrt{3}}{2\sqrt{2}} & \frac{-\sqrt{3}}{2\sqrt{2}}  & \frac{\sqrt{3}}{\sqrt{2}} \end{bmatrix} $$

###  3.

Yes, the matrix A is invertible. The proof is, we found matrix's (previous exercise) to fill the conditions:
$$ A = PDP^{-1}$$
so we have the matrix P with linear independt vectors (Eingevectors of A) and the diagonal matrix D (Eingevalues of A). So it is suficient to affirm **A is invertible**.

- Now we have to write $A^{-1}$ in terms of **P** and **D**.

$$ A = PDP^{-1} \rightarrow (A)^{-1} = (PDP^{-1})^{-1} $$ 

$$\boxed{ A^{-1} = PD^{-1}P^{-1} }$$

I just applied the the exponent **-1** in both sides of the equation. So we have the expression for $A^{-1}$ in terms of **P** and **D**

$${A^{-1}} = \begin{bmatrix} \frac{-1}{4} & \frac{3}{4} & \frac{-1}{4} \\ \frac{3}{4} & \frac{-1}{4} & \frac{-1}{4} \\ \frac{-1}{4} & \frac{-1}{4}  & \frac{3}{4} \end{bmatrix} $$

- So let's starting calculating the **Characteristic Polynomial of $A^{-1}$**:

$$p(\lambda)= det (A^{-1}- \lambda I)$$

$$p(\lambda)= det \begin{bmatrix} \frac{-1}{4}- \lambda & \frac{3}{4} & \frac{-1}{4} \\ \frac{3}{4} & \frac{-1}{4} - \lambda & \frac{-1}{4} \\ \frac{-1}{4} & \frac{-1}{4}  & \frac{3}{4}- \lambda \end{bmatrix} $$

$$\boxed { p(\lambda) = \frac{-4\lambda^3 + \lambda^2 + 4\lambda - 1}{4}}$$

- Now we can calculate the **Eingevalues**:

We have to find the $\lambda$'s to turn $p(\lambda) = 0$.


We can easily identify $\boxed {\lambda_{1} = \frac{1}{4}}$, $\boxed {\lambda_{2} = 1}$ and $\boxed {\lambda_{3} = -1}$ are eingevalues for this $p(\lambda)$

###  4.

In [59]:
import numpy as np
from scipy.optimize import minimize

In [60]:

# define matrix A using Numpy arrays
A = np.array([[1, 2, 1],
 [2, 1, 1],
 [1, 1, 2]])

In [61]:
from numpy import linalg as la

eig_val, eig_vect = la.eig(A)

# Now we can find the Eingevalues:
print(eig_val)

[ 4. -1.  1.]


In [62]:
# Now we can find the Orthonormalized Eingevectors:

print(eig_vect)

[[-5.77350269e-01 -7.07106781e-01 -4.08248290e-01]
 [-5.77350269e-01  7.07106781e-01 -4.08248290e-01]
 [-5.77350269e-01  1.02381169e-16  8.16496581e-01]]


In [63]:
# Now we can find the Inverse:

inverse_A = la.inv(A)

print(inverse_A)

[[-0.25  0.75 -0.25]
 [ 0.75 -0.25 -0.25]
 [-0.25 -0.25  0.75]]


## 3 Non Constrained Optimization and Convexity

###  1. and 2.

We have to check if the function $f$ is convex:

$$\boxed {f : (x_{1},x_{2},x_{3}) \rightarrow f(x_{1},x_{2},x_{3}) = x_{1}^{4}+(x_{1}+x_{2})^{2}+(x_{1}+x_{3})^{2}}$$

First, lets analyze the gradient and see the extrema points. 

$$
\nabla f(\left.x_{1}, x_{2}, x_{3}\right)=\left[\begin{array}{c}
\dfrac{\partial f}{\partial x_1}(\left.x_{1}, x_{2}, x_{3}\right)\\
\dfrac{\partial f}{\partial x_2}(\left.x_{1}, x_{2}, x_{3}\right) \\
\dfrac{\partial f}{\partial x_3}(\left.x_{1}, x_{2},  x_{3}\right) 
\end{array}\right]
$$

$$
\nabla f(\left.x_{1}, x_{2}, x_{3}\right)=
\begin{bmatrix} 4x_{1}^3+4x_1+2x_{2}+2x_{3}\\ 2x_{1}+2x_{2} \\ 2x_{1}+2x_{3} \end{bmatrix}
$$

To find the extrema point, we need to assume $\nabla f(\left.x_{1}, x_{2}, x_{3}\right)= 0$. So:

(i) $ 4x_{1}^3+4x_1+2x_{2}+2x_{3} = 0$

(ii) $ 2x_{1}+2x_{2} = 0 $

(iii) $ 2x_{1}+2x_{3} = 0 $

For **(i)** and **(ii)**:

$x_{1} = - x_{2}$

$x_{1} = - x_{3}$

Then : $x_{2} = x_{3}$

Analyzing (i), (ii) and (iii) we can easily see the only point satisfying is : $\boxed{f(0,0,0)=0}$

To analyze the function convexity, we have to look the **Hessian matrix** of the function $f$. The **Hessian matrix** is defined as below:

$$ Hessian = \begin{bmatrix}
\frac{\partial^2 f}{\partial x_1^2} & \frac{\partial^2 f}{\partial x_1\partial x_2 } &
\frac{\partial^2 f}{\partial x_1\partial x_3 }
\\ \frac{\partial^2 f}{\partial x_2\partial x_1} & \frac{\partial^2 f}{\partial x_2^2} &
\frac{\partial^2 f}{\partial x_2\partial x_3 } 
\\ \frac{\partial^2 f}{\partial x_3\partial x_1} & \frac{\partial^2 f}{\partial x_3\partial x_2} &
\frac{\partial^2 f}{\partial x_3^2} 
\end{bmatrix}
$$

Calculating the partial derivatives, we have as result the matrix below:

$$ Hessian = \begin{bmatrix} 12x_{1}^{2}+4 & 2 & 2 \\ 2 & 2 & 0 \\ 2 & 0 & 2 \end{bmatrix}$$

$$ det Hessian = 48x_1^{2} $$

The determinant will be non negative for any number, but could be zero for $x_1 = 0$, so the function is **Convex semi-definite**

Now let's calculate the determinants, analyzing the minors of the Hessian matrix above.

$$ det A_1 = det \begin{bmatrix} 12x_1^{2} +4 \end{bmatrix} = 12x_1^{2} +4 $$

$$ det A_2 = det \begin{bmatrix} 12x_1^{2}  +4 & 2 \\ 2 & 2 \end{bmatrix} = 24x_1^{2} +4 $$

$$ det A_3 = det \begin{bmatrix} 12x_1^{2}  +4 & 2 &2 \\ 2 & 2 & 0 \\ 2 & 0 & 2 \end{bmatrix} = 48x_1^{2} $$

We know the extrema is (0,0,0), so we can substitute in the results of $detA_1$, $detA_2$ and $detA_3$:

$detA_1 = 4$

$detA_2 = 4$

$detA_3 = 0$

So, these determinants ($detA_1, detA_2, detA_3$)  are all nonnegative then the **matrix is positive semidefinite**

Extrema points **(0,0,0)**

### Testing with Python

In [153]:
#using the file "Class_Participation_1.ipynb" available in Module 4. Adaptating the code to use as optimizer

In [154]:
#function

f = lambda x: x[0]**2 + (x[0]+x[1])**2 + (x[0]+x[2])**2

In [155]:
#we don't have constraints in this problem

In [156]:
#extrema point

x_0 = np.array([0,0,0])


res = minimize(f,x_0,method = 'BFGS')
print(res)

      fun: 0.0
 hess_inv: array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])
      jac: array([4.47034836e-08, 1.49011612e-08, 1.49011612e-08])
  message: 'Optimization terminated successfully.'
     nfev: 4
      nit: 0
     njev: 1
   status: 0
  success: True
        x: array([0., 0., 0.])


## 4 Optimization with Equality Constraints

###  1.

We have to min $x_1,x_2,x_3$:

$$\boxed {f(x_1,x_2,x_3) = x_1 + x_2 + 2x_3^{2}}$$

Using the constraints:


$$\boxed {x_1 = 1 \rightarrow h_1(x_1) = x_1-1=0}$$
$$\boxed {x_1^{2}+x_2^{2} = 1 \rightarrow h_2(x_1,x_2) = x_1^{2}+x_2^{2} -1=0}$$

So let's first analyze the constraints, $h_1(x_1)$ and $h_2(x_1,x_2)$, to check the first equation: 

From $h_1(x_1)$ it's pretty easy to identify $\boxed{x_1=1}$. Now let's use this result in $h_2(x_1,x_2)$:

$1^2+x_2^{2}=1 \rightarrow x_2^{2} = 0 \rightarrow \boxed {x_2 = 0}$

Now we know the 2 out of 3 points to minimize this function using this problem constraints, in this case **(1,0,$x_3$)**. Now lets substitute in the function $f(x_1,x_2,x_3)$ this points:

$f(1,0,x_3) = 1 + 0 +2x_3^{2} \rightarrow f(1,0,x_3) = 1+2x_3^{2}$

Now we have to calculate the gradient to see the minimum point for this function:

$\frac{\partial f}{\partial x_3} = 4x_3 \rightarrow 4x_3 = 0 \rightarrow x_3 = 0$

So the minimum point for this function is $\boxed {(1,0,0)}$

$\boxed {f(1,0,0) = 1}$

Now let's try to use the Lagrangian approach:



$L(x_1,x_2,x_3,\lambda_1,\lambda_2) = f(x_1,x_2,x_3)+\lambda_1(h(x_1))+ \lambda_2(h(x_1,x_2))$

$L(x_1,x_2,x_3,\lambda_1,\lambda_2) = x_1 + x_2 + 2x_3^{2}+\lambda_1(x_1-1)+\lambda_2(x_1^{2}+x_2^{2}-1)$

Now we should calculate the gradient of $L$.

$$
\nabla L(\left.x_{1}, x_{2}, x_{3},\lambda_1,\lambda_2\right)=(1+\lambda_1+2\lambda_2x_1,1+2\lambda_2x_2,4x_3,x_1-1,(x_1^{2}+x_2^{2}-1))$$

To find the min of the function : $\nabla L(\left.x_{1}, x_{2}, x_{3},\lambda_1,\lambda_2\right)=0$

$\boxed{4x_3 = 0 \rightarrow x_3 = 0}$

$\boxed{x_1-1 = 0 \rightarrow x_1 = 1}$

$\boxed{(x_1^{2}+x_2^{2}-1) = 0 \rightarrow x_2 = 0}$

for $\forall \lambda_1, \lambda_2$

$(x_1,x_2,x_3) \rightarrow (1,0,0)$

The solution is not unique for $\lambda_1,\lambda_2$, so **we cannot use Lagrangian approach in this case**, because we cannot use an unique value for $\lambda_1,\lambda_2$ to satisfy the minimum value.

### Testing with Python

In [158]:
#using the file "Class_Participation_1.ipynb" available in Module 4. Adaptating the code to use as optimizer

In [159]:
#function

f = lambda x: x[0]+x[1]+2*x[2]**2

In [160]:
#constraints

con = ({'type': 'eq','fun': lambda x: np.array(x[0]-1)},
        {'type': 'eq','fun': lambda x: np.array(x[0]**2 + x[1]**2 - 1)})

In [161]:
#(x1,x2,x3) -> (1,0,0)
x_0 = [1,0,0]

b = (-10,10) 
bounds = (b,b,b)

res = minimize(f,x_0,method = 'SLSQP',bounds=bounds,constraints=con)
print(res)

     fun: 1.0
     jac: array([1.00000000e+00, 1.00000000e+00, 2.98023224e-08])
 message: 'Optimization terminated successfully'
    nfev: 4
     nit: 1
    njev: 1
  status: 0
 success: True
       x: array([1., 0., 0.])


###  2.

We have to min $x_1,x_2$:

$$\boxed {f(x_1,x_2) = 2x_1^{2} + x_2^{2}}$$

Using the constraints:


$$\boxed {x_1 + x_2 = 1 \rightarrow h(x_1,x_2) = x_1+x_2-1=0}$$

Now let's try to use the Lagrangian approach:

$L(x_1,x_2\lambda_1,) = f(x_1,x_2,x_3)+\lambda(h(x_1))$

The Lagrangian is:

$$\boxed{L(x_1,x_2,\lambda) = 2x_1^{2} + x_2^{2} + \lambda(x_1+x_2-1)}$$

Now we have to get the gradient of L and then make equal to zero to find the minimum

$\nabla L(\left.x_{1}, x_{2},\lambda\right)=0$

$\nabla L(\left.x_{1}, x_{2},\lambda\right)=(4x_1-\lambda,2x_2-\lambda,1-x_1-x_2)$

$\boxed {x_1 = \frac{1}{3}, x_2 = \frac{2}{3}, \lambda = \frac{4}{3}}$

So the minimum point of the Lagrangian using this coordinates above is:

$L\left(\frac{1}{3},\frac{2}{3},\frac{4}{3}\right) = 2\left(\frac{1}{3}\right)^2+\left(\frac{2}{3}\right)^2+\frac{4}{3}\left(\frac{1}{3}+\frac{2}{3}-1\right)$

$\boxed{L\left(\frac{1}{3},\frac{2}{3},\frac{4}{3}\right) = \frac{2}{9} + \frac{4}{9} = \frac{6}{9} = \frac{2}{3}}$

$\boxed {f\left(\frac{1}{3},\frac{2}{3}\right) = \frac{2}{3} \sim 0.67}$

**Now let's change change the constraint.**

$$\boxed {x_1 + x_2 = 1.05 \rightarrow h(x_1,x_2) = x_1+x_2-1.05=0}$$

So the new Lagrangian is:

$$\boxed{L(x_1,x_2,\lambda) = 2x_1^{2} + x_2^{2} + \lambda(x_1+x_2-1.05)}$$

Now we have to get the gradient of L and then make equal to zero to find the minimum

$\nabla L(\left.x_{1}, x_{2},\lambda\right)=0$

$\nabla L(\left.x_{1}, x_{2},\lambda\right)=(4x_1-\lambda,2x_2-\lambda,1.05-x_1-x_2)$

$\boxed {x_1 = 0.35, x_2 = 0.7, \lambda = -1.4}$

$\boxed {f\left(0.35,0.7\right) = 2(0.35)^2+(0.7)^2 = 0.735}$

So, if the constraint changes from 1 to 1.05, the minimum changes from $\sim$0.67 to 0.735

### Testing with Python

In [162]:
#using the file "Class_Participation_1.ipynb" available in Module 4. Adaptating the code to use as optimizer

In [163]:
#function

f = lambda x: 2 * x[0]**2 +x[1]**2

In [164]:
#constraints

con = ({'type': 'eq','fun': lambda x: np.array(x[0]+x[1]-1)})

In [165]:
#(x1,x2) -> (0.35,0.70)
x_0 = [0.35,0.70]

b = (-10,10) 
bounds = (b,b)

res = minimize(f,x_0,method = 'SLSQP',bounds=bounds,constraints=con)
print(res)

     fun: 0.6666666666666667
     jac: array([1.33333337, 1.33333336])
 message: 'Optimization terminated successfully'
    nfev: 10
     nit: 3
    njev: 3
  status: 0
 success: True
       x: array([0.33333333, 0.66666667])


###  3.

###  (a)

We have to max $\omega_1,\omega_2$:

$$\boxed {R_P(\omega_1,\omega_2) = \rho_1\omega_1 + \rho_2\omega_2}$$

Subject to:


$$\boxed {\sqrt{ \sigma_1^2\omega_1^2 + \sigma_2^2\omega_2^2 + 2\rho_12\sigma_1\sigma_2\omega_1\omega_2} = \sigma_T \rightarrow h_1(\omega_1,\omega_2) = \sqrt{ \sigma_1^2\omega_1^2 + \sigma_2^2\omega_2^2 + 2\rho_{12}\sigma_1\sigma_2\omega_1\omega_2} - \sigma_T } $$

$$\boxed {\omega_1 + \omega_2 = 1 \rightarrow h_2(\omega_1,\omega_2) =\omega_1 + \omega_2 -1}$$

Now we can write the Lagrangian:

$$L(\omega_1,\omega_2,\lambda_1,\lambda_2) = R_P(\omega_1,\omega_2) + \lambda_1 h_1(\omega_1,\omega_2)+ \lambda_2 h_2(\omega_1,\omega_2) $$

$$L(\omega_1,\omega_2,\lambda_1,\lambda_2) = (\rho_1\omega_1 + \rho_2\omega_2) + \lambda_1\left(\sqrt{ \sigma_1^2\omega_1^2 + \sigma_2^2\omega_2^2 + 2\rho_{12}\sigma_1\sigma_2\omega_1\omega_2} - \sigma_T\right)+\lambda_2(\omega_1 + \omega_2 -1)$$

**(i)** $\frac{\partial L}{\partial \omega_1} = \rho_1 + \frac{\lambda_1}{2} \frac{2\sigma_1^2\omega_1 + 2\rho_{12}\sigma_1\sigma_2\omega_2}{\sqrt{ \sigma_1^2\omega_1^2 + \sigma_2^2\omega_2^2 + 2\rho_{12}\sigma_1\sigma_2\omega_1\omega_2}} + \lambda_2 = 0 $

**(ii)** $\frac{\partial L}{\partial \omega_2} = \rho_2 + \frac{\lambda_1}{2} \frac{2\sigma_2^2\omega_2 + 2\rho_{12}\sigma_1\sigma_2\omega_1}{\sqrt{ \sigma_1^2\omega_1^2 + \sigma_2^2\omega_2^2 + 2\rho_{12}\sigma_1\sigma_2\omega_1\omega_2}} + \lambda_2 = 0 $

**(iii)** $\frac{\partial L}{\partial \lambda_1} = \sqrt{ \sigma_1^2\omega_1^2 + \sigma_2^2\omega_2^2 + 2\rho_{12}\sigma_1\sigma_2\omega_1\omega_2} - \sigma_T = 0 $

**(iv)** $\frac{\partial L}{\partial \lambda_2} = \omega_1 + \omega_2 -1 = 0$

**Message to Professor Papa** :  Professor I tried to solve this problem, but I got stuck in how to find the formula for $\omega_1$ and $\omega_2$ , unfortunately was impossible to solve the other questions without this result. I watched the classes and looked in the books but unfortunately I couldn't get the solution for this problem. 
This situation was a bit complicated, frustrating because I didn't solve the problem, but I tried until the last minutes of Sunday.

## 5 Optimization with Inequality Constraints

###  1.

We have to min $x_1,x_2$:

$$\boxed {f(x_1,x_2) = (x_1-2)^{2} + 2(x_2-1)^{2}}$$

Using the constraints:


(i)$\boxed {x_1 + 4x_2 \leqslant 3}$

(ii)$\boxed {x_1 \geqslant x_2}$

It's easier to rearrange **(ii)**:

$\boxed {x_1-x_2 \geqslant 0 \rightarrow x_2-x_1 \leqslant 0}$

Now we can write the Lagrangian for this problem:

$\boxed{L(x_1,x_2,\lambda_1, \lambda_2) = (x_1-2)^{2} + 2(x_2-1)^{2}+\lambda_1(x_1+4x_2-3)+\lambda_2(x_2-x_1)}$

Since we have the Lagrangian, now we can calculate the gradient:

$\frac{\partial L}{\partial x_1}= 2x_1- 4 - \lambda_1 - \lambda_2$

$\frac{\partial L}{\partial x_2} = 4x_2-4+4\lambda_1+\lambda_2$

$\lambda_1(x_1+4x_2-3)=0$

$\lambda_2(x_2-x_1) = 0$

Now, we have 4 cases to analyze. Analyzing all the cases we get:

$\boxed{x_1 = \frac{3}{5}}$

$\boxed{x_2 = \frac{3}{5}}$

$\boxed{f(x_1,x_2) = \frac{53}{25}}$

### Testing with Python now:

In [166]:
#using the file "Class_Participation_1.ipynb" available in Module 4. Adaptating the code to use as optimizer

In [176]:
#function

f = lambda x: (x[0]-2)**2+2*((x[1]-1)**2)

In [177]:
#constraints

con = ({'type': 'ineq','fun': lambda x: np.array(3 - x[0] - 4 * x[1])},
        {'type': 'ineq','fun': lambda x: np.array(x[1] - x[0])})

In [178]:
#(x1,x2) -> (0,0)
x_0 = [0,0]

b = (-10,10) 
bounds = (b,b)

res = minimize(f,x_0,method = 'SLSQP',bounds=bounds,constraints=con)
print(res)

     fun: 2.2799999999998986
     jac: array([-2.79999998, -1.59999996])
 message: 'Optimization terminated successfully'
    nfev: 6
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.6, 0.6])


In [170]:
# results in the simulation are different than I get by hand

###  2.

We have to max $x_1,x_2$:

$$\boxed {f(x_1,x_2) = 5 - x_1^{2} - x_1x_2 - 3x_2^{2}}$$

Using the constraints:


$$\boxed {x_1,x_2\geqslant 0 }$$
$$\boxed {x_1x_2 \geqslant 2 }$$

Now we can have the gradients:

$\nabla f(x_1,x_2) = (-2x_1-x_2,-x_1-6x_2) $

$\nabla h_1(x_1,x_2) =(1,0) $

$\nabla h_2(x_1,x_2) =(0,1) $

$\nabla h_3(x_1,x_2) = (x_2,x_1) $

Now we can write the Lagrangian for this problem:

$\boxed{L(x_1,x_2,\lambda_1, \lambda_2) = (5 - x_1^{2} - x_1x_2 - 3x_2^{2})+\lambda_1(x_1x_2-2)+\lambda_2x_1+\lambda_3x_2}$

$\frac{\partial L}{\partial x_1}= -2x_1- x_2+\lambda_1x_2+\lambda_2 $

$\frac{\partial L}{\partial x_2} = -x_1-6x_2+\lambda_1x_1+\lambda_3$

$\lambda_1(x_1x_2-2)=0$

$\lambda_2x_1 = 0$

$\lambda_3x_2 = 0$

Analyzing case 1 and case 2:

$\boxed{x_1 = 1.8170}$

$\boxed{x_2 = 1.10}$

$\boxed{f(x_1,x_2) = 3.9370}$

### Testing with Python now:

In [172]:
#using the file "Class_Participation_1.ipynb" available in Module 4. Adaptating the code to use as optimizer

In [173]:
#function

f = lambda x: x[0]**2+x[0]*x[1]+3*(x[1]**2)-5

In [174]:
#constraints

con = ({'type': 'ineq','fun': lambda x: np.array(x[0] *  x[1] - 2)})

In [175]:
#(x1,x2) -> (1,2)
x_0 = [1,2]

b = (-10,10) 
bounds = (b,b)

res = minimize(f,x_0,method = 'SLSQP',bounds=bounds,constraints=con)
print(res)

     fun: 3.928203223666145
     jac: array([4.79698992, 8.30862856])
 message: 'Optimization terminated successfully'
    nfev: 302
     nit: 78
    njev: 76
  status: 0
 success: True
       x: array([1.86121003, 1.07456975])
